name: CraftBook
main: com.sk89q.craftbook.bukkit.CraftBookPlugin
version: '${project.version}-${describe}'
dev-url: http://dev.bukkit.org/server-mods/craftbook/
softdepend: [WorldEdit, WorldGuard, ProtocolLib, Vault]
commands:
